# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 529d0f419748d26c277ccbfe04c34a2fdbd7cf0f87366a2324aaa224ce8d9cbb8f2b3a92707dfbcb475690080c827be25d0ccd8997c4e358f718c7ef0406d355

test:
  secret_key_base: ceca2e3cff08445fd9f66661700da5e632af34d6fb5422fedb23bdd4cdb3756d1d0828da8b2346e8fbaa165414d2301ce52e575fc1010711f4bd36028e94026f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
